export { default as Dashboard } from './Dashboard'
export { default as Users } from './Users'
export { default as Loans } from './Loans'
export { default as Payments } from './Payments'
export { default as Reports } from './Reports'
export { default as Settings } from './Settings'
